export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  seoKeywords?: string[];
  image: string;
  date: string;
  author: string;
  readTime: string;
};

export const BLOG_CATEGORIES = [
  "전체",
  "미술치료",
  "ACT",
  "증상별 가이드",
  "실습 가이드",
] as const;

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "grief-art-therapy-loss-recovery",
    title: "상실의 시간을 지나갈 때, 그림이 조용히 담아주는 마음",
    excerpt: "상실을 겪는 성인과 가족에게 미술치료가 마음의 시간을 담아주는 방식을 표현과 관계의 관점에서 설명합니다.",
    category: "미술치료",
    seoKeywords: ["미술치료", "애도 미술치료", "상실 회복", "성인 미술치료", "가족 돌봄 미술치료"],
    image: "/blog-illustrations/grief-art-therapy-loss-recovery.svg",
    date: "2026년 7월 16일",
    author: "고은별",
    readTime: "6분",
  },
  {
    slug: "art-therapy-not-drawing-skill",
    title: "미술치료는 그림을 잘 그리는 시간이 아닙니다",
    excerpt: "미술치료를 처음 떠올릴 때 생기는 오해를 풀고, 그림 실력보다 표현의 과정과 치료적 관계가 왜 중요한지 따뜻하게 안내합니다.",
    category: "미술치료",
    seoKeywords: ["미술치료", "아동 미술치료", "미술치료 오해", "그림 심리", "ACT ART CENTER"],
    image: "/blog-illustrations/art-therapy-not-drawing-skill.svg",
    date: "2026년 7월 13일",
    author: "고은별",
    readTime: "6분",
  },
  {
    slug: "unfinished-drawing-art-therapy",
    title: "완성되지 않은 그림도 마음의 이야기입니다",
    excerpt: "미술치료에서 그림의 완성도보다 표현의 과정이 왜 소중한지, 아이와 어른의 마음을 바라보는 따뜻한 관점을 전합니다.",
    category: "미술치료",
    seoKeywords: ["미술치료", "미술치료사", "아동 미술치료", "정서 표현", "부모 상담", "그림 심리"],
    image: "/blog-illustrations/unfinished-drawing-art-therapy.svg",
    date: "2026년 7월 12일",
    author: "고은별",
    readTime: "6분",
  },
  {
    slug: "safe-paper-art-therapy-room",
    title: "미술치료실에서 종이가 안전한 자리가 되는 순간",
    excerpt: "미술치료에서 종이와 재료가 평가의 대상이 아니라 안전하게 마음을 올려놓는 자리가 되는 과정을 설명합니다.",
    category: "미술치료",
    seoKeywords: ["미술치료", "미술치료실", "안전한 표현", "치료적 관계", "서초 미술치료", "성인 미술치료"],
    image: "/blog-illustrations/safe-paper-art-therapy-room.svg",
    date: "2026년 7월 11일",
    author: "고은별",
    readTime: "6분",
  },
  {
    slug: "child-lines-colors-art-therapy",
    title: "아이의 선과 색을 천천히 보는 미술치료의 이유",
    excerpt: "아이의 그림을 결과물로만 보지 않고, 재료를 고르고 선을 긋고 지우는 과정까지 살피는 미술치료의 관점을 안내합니다.",
    category: "미술치료",
    seoKeywords: ["아동 미술치료", "미술치료 과정", "아이 그림 해석", "정서표현 미술치료", "서초 미술치료"],
    image: "/blog-illustrations/child-lines-colors-art-therapy.svg",
    date: "2026년 7월 10일",
    author: "고은별",
    readTime: "6분",
  },
  {
    slug: "caregiver-fatigue-art-therapy",
    title: "돌봄으로 지친 마음을 색으로 잠시 쉬게 하는 시간",
    excerpt: "가족을 돌보는 과정에서 쌓이는 피로와 감정을 미술 활동으로 안전하게 알아차리고, 일상 속 작은 자기돌봄으로 연결하는 방법을 안내합니다.",
    category: "미술치료",
    seoKeywords: ["돌봄 피로", "가족 돌봄", "성인 미술치료", "정서조절", "자기돌봄", "보호자 상담"],
    image: "/blog-illustrations/caregiver-fatigue-art-therapy.svg",
    date: "2026년 7월 9일",
    author: "고은별",
    readTime: "7분",
  },
  {
    slug: "parent-words-for-child-drawing",
    title: "아이 그림 앞에서 부모가 먼저 건넬 수 있는 말",
    excerpt: "아이의 그림을 따뜻하게 바라보고, 아이가 자기 이야기를 안전하게 꺼낼 수 있도록 부모가 건넬 수 있는 질문과 관찰법을 소개합니다.",
    category: "미술치료",
    seoKeywords: ["아이 그림 해석", "부모 대화법", "아동 미술치료", "아이 감정 표현", "그림 심리"],
    image: "/blog-illustrations/parent-words-for-child-drawing.svg",
    date: "2026년 7월 8일",
    author: "고은별",
    readTime: "7분",
  },
  {
    slug: "art-therapy-science",
    title: "미술치료 효과의 과학적 근거",
    excerpt: "Kaimal의 코르티솔 연구, Shella의 병상 미술치료 데이터, van der Kolk의 브로카 발견까지. 미술치료가 어디까지 과학적으로 입증되어 있는지 임상가의 시선으로 정리했습니다.",
    category: "미술치료",
    seoKeywords: ["미술치료 효과", "미술치료 사례", "정신건강 미술치료"],
    image: "/blog-illustrations/art-therapy-science.svg",
    date: "2026년 4월 10일",
    author: "고은별",
    readTime: "11분",
  },
  {
    slug: "act-6-processes",
    title: "ACT의 6가지 핵심 프로세스",
    excerpt: "수용, 탈융합, 현재 순간 접촉, 맥락으로서의 자기, 가치, 전념 행동. Hayes의 헥사플렉스를 미술치료 장면과 연결하며 하나씩 풀어 봅니다.",
    category: "ACT",
    seoKeywords: ["수용전념치료", "수용전념치료 기법", "수용전념치료 육각형", "ACT 미술치료"],
    image: "/blog-illustrations/act-6-processes.svg",
    date: "2026년 4월 5일",
    author: "고은별",
    readTime: "10분",
  },
  {
    slug: "anxiety-art-therapy",
    title: "불안을 그림으로 표현하기",
    excerpt: "불안은 없애는 대상이 아니라 형태를 주는 대상입니다. Huang의 최신 메타분석과 폴리베이갈 이론을 바탕으로, 불안에 색과 모양을 입히는 세 가지 실습을 소개합니다.",
    category: "증상별 가이드",
    image: "/blog-illustrations/anxiety-art-therapy.svg",
    date: "2026년 3월 28일",
    author: "고은별",
    readTime: "9분",
  },
  {
    slug: "mindfulness-drawing",
    title: "마음챙김 드로잉: 현재에 머무르기",
    excerpt: "가부좌 명상이 어렵게 느껴지시는 분들을 위해. Kabat-Zinn의 MBSR과 Csikszentmihalyi의 몰입 이론을 바탕으로, 펜 한 자루로 시작하는 다섯 가지 드로잉 실습을 안내합니다.",
    category: "실습 가이드",
    seoKeywords: ["마음챙김 미술치료", "마음챙김 드로잉", "미술치료 방법"],
    image: "/blog-illustrations/mindfulness-drawing.svg",
    date: "2026년 3월 20일",
    author: "고은별",
    readTime: "9분",
  },
  {
    slug: "trauma-art-expression",
    title: "트라우마와 미술 표현의 관계",
    excerpt: "트라우마 기억 앞에서 말이 막히는 신경학적 이유와, 미술이 그 자리에 다리를 놓을 수 있는 근거. Schouten과 Malchiodi의 연구를 통해 페이싱 원칙을 살펴봅니다.",
    category: "미술치료",
    seoKeywords: ["트라우마 미술치료", "미술치료 사례", "정신건강 미술치료"],
    image: "/blog-illustrations/trauma-art-expression.svg",
    date: "2026년 3월 15일",
    author: "고은별",
    readTime: "10분",
  },
  {
    slug: "values-vision-board",
    title: "가치 탐색: 비전 보드 만들기",
    excerpt: "머리로 생각한 가치와 몸이 움직이는 가치 사이의 간격을 좁히는 도구. ACT의 가치 명료화 연구를 바탕으로 집에서 따라 할 수 있는 네 단계 비전 보드 가이드를 드립니다.",
    category: "ACT",
    image: "/blog-illustrations/values-vision-board.svg",
    date: "2026년 3월 8일",
    author: "고은별",
    readTime: "9분",
  },
];
